version: "3"
services:
  simple:
    build:
      context: .
      dockerfile: sp.Dockerfile
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # node-app:
  #   build:
  #     context: .
  #     dockerfile: node.Dockerfile
  #   ports:
  #     - 3000:3000
  # nginx-app:
  #   build:
  #     context: .
  #     dockerfile: nginx.Dockerfile
  #   ports:
  #     - 4000:80
